# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1c519d9adf7420d0dba5892898338b80dc5fa72d9b8ae6b674a580a880fd3038f8a16e07a6e725fcb62b76365c884abe5222ed96230432163c85e2f19bcf931

test:
  secret_key_base: 9316acfee20361ba6df9c13919a68bfd57f3f27291c4ae2478820287efa762164ebd3f3dcad8d852689acc0be05a3273a2e9979d22f2e1b22a615c4ed9b9c901

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
